import './globals.css'
import { Analytics } from '@vercel/analytics/react';
import Homepage from './components/Homepage';
import NewWay from './components/NewWay';
import Gallery from './components/Gallery';


export const metadata = {
  title: 'Zerttesh',
  description: 'Generated by Zerttesh',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-black'>
        {children}
        <Homepage/>
        <NewWay/>
        <Gallery/>
 
        <Analytics />
      </body>
    </html>
  )
}
