import './globals.css'
import { Analytics } from '@vercel/analytics/react';
import Mobile from './mobilepade';
export const metadata = {
  title: 'Zerttesh',
  description: 'Generated by Zerttesh',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
